### ISSUE TITLE
ugroup error /メーリングリスト表示時のエラー

### ISSUE THREAD

**Issue by kotarobo** [ucchyocean/UndineMailer#106]
1.16.5にてメールを作成中に以下のエラーが出ました
```[20:21:34] [Server thread/INFO]: kotarobo_ issued server command: /ugroup list 1 /umail to group 1
[20:21:34] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ugroup' in plugin UndineMailer v1.10.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Name cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.getOfflinePlayer(CraftServer.java:1564) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:928) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bitbucket.ucchy.undine.sender.MailSenderPlayer.getOfflinePlayer(MailSenderPlayer.java:123) ~[?:?]
	at org.bitbucket.ucchy.undine.sender.MailSenderPlayer.getName(MailSenderPlayer.java:79) ~[?:?]
	at org.bitbucket.ucchy.undine.group.GroupData.getHoverText(GroupData.java:225) ~[?:?]
	at org.bitbucket.ucchy.undine.group.GroupManager.displayGroupSelection(GroupManager.java:396) ~[?:?]
	at org.bitbucket.ucchy.undine.command.GroupCommand.doListCommand(GroupCommand.java:292) ~[?:?]
	at org.bitbucket.ucchy.undine.command.GroupCommand.onCommand(GroupCommand.java:75) ~[?:?]
	at org.bitbucket.ucchy.undine.UndineMailer.onCommand(UndineMailer.java:130) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-457]
	... 19 more
```
チャット画面にはAn internal error occurredが出ています。
https://gyazo.com/bbf22afa56ba6450eaea0d0ebd581c82

**Comment by kotarobo** [comment]
とても恥ずかしいミスが原因でした；
失礼しました！

**Comment by kotarobo** [comment]
誤ってクローズしてしまいました
PCGF_PluginLibの仕様が変わった際にLikeプラグインの方でも動かない不具合が出たので、同様の問題かもしれません
