### ISSUE TITLE
グループの詳細を確認するとき、変更権限がなくて送信権限が有るプレイヤーだと、IndexOutOfBoundsExceptionが発生する

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/UndineMailer#12]
単純な実装ミスっぽい。
スタックトレースは下記の通り。

<pre>
[12:38:12] [Server thread/INFO]: Player330 issued server command: /ugroup detail Test
[12:38:12] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ugroup' in plugin UndineMailer v1.2.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:624) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:34) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_05]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_05]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:643) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:638) ~[?:1.8.0_05]
	at java.util.ArrayList.get(ArrayList.java:414) ~[?:1.8.0_05]
	at org.bitbucket.ucchy.undine.group.GroupManager.displayGroupDetailReadOnly(GroupManager.java:395) ~[?:?]
	at org.bitbucket.ucchy.undine.group.GroupCommand.doDetailCommand(GroupCommand.java:301) ~[?:?]
	at org.bitbucket.ucchy.undine.group.GroupCommand.onCommand(GroupCommand.java:64) ~[?:?]
	at org.bitbucket.ucchy.undine.UndineMailer.onCommand(UndineMailer.java:101) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	... 14 more
</pre>

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
