### ISSUE TITLE
パターンを1つ以上塗ったバナーをメールに添付して送信した後、サーバー再起動するとエラーが起こる。

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/UndineMailer#24]
パターンを1つ以上塗ったバナーをメールに添付して送信した後、サーバー再起動するとエラーが起こる。

スタックトレースは下記の通り。
<pre>
[14:15:59] [pool-3-thread-12/WARN]: org.apache.commons.lang.UnhandledException: Plugin UndineMailer v1.3.1 generated an exception while executing task 34
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:638)
	at java.util.ArrayList.set(ArrayList.java:429)
	at org.bukkit.craftbukkit.v1_8_R1.inventory.CraftMetaBanner.setPattern(CraftMetaBanner.java:139)
	at org.bitbucket.ucchy.undine.item.ItemConfigParserV18.addBannerInfoToItem(ItemConfigParserV18.java:52)
	at org.bitbucket.ucchy.undine.item.ItemConfigParser.getItemFromSection(ItemConfigParser.java:295)
	at org.bitbucket.ucchy.undine.MailData.loadFromConfigSection(MailData.java:265)
	at org.bitbucket.ucchy.undine.MailData.load(MailData.java:224)
	at org.bitbucket.ucchy.undine.MailManager$1.run(MailManager.java:87)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

</pre>

どうやら、BannerMetaへのパターン設定が、正しく動作していないようだ。

**Comment by ucchyocean** [comment]
追加。
バナーが添付されているメールを開くと起こる。
<pre>
[14:27:56] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'umail' in plugin UndineMailer v1.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:624) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:34) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_05]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_05]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:643) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: java.lang.NullPointerException
	at org.bitbucket.ucchy.undine.item.ItemConfigParserV18.addBannerInfoToSection(ItemConfigParserV18.java:83) ~[?:?]
	at org.bitbucket.ucchy.undine.item.ItemConfigParser.setItemToSection(ItemConfigParser.java:453) ~[?:?]
	at org.bitbucket.ucchy.undine.MailData.saveToConfigSection(MailData.java:204) ~[?:?]
	at org.bitbucket.ucchy.undine.MailData.save(MailData.java:142) ~[?:?]
	at org.bitbucket.ucchy.undine.MailManager.saveMail(MailManager.java:370) ~[?:?]
	at org.bitbucket.ucchy.undine.MailManager.displayMail(MailManager.java:352) ~[?:?]
	at org.bitbucket.ucchy.undine.command.UndineReadCommand.runCommand(UndineReadCommand.java:95) ~[?:?]
	at org.bitbucket.ucchy.undine.command.UndineCommand.onCommand(UndineCommand.java:88) ~[?:?]
	at org.bitbucket.ucchy.undine.UndineMailer.onCommand(UndineMailer.java:105) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	... 14 more
</pre>

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
