### ISSUE TITLE
Cannot send potion as attachment item.

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/UndineMailer#36]
Cannot send potion as attachment item.

Stack trace is as follows:
<pre>
[19:33:56] [pool-3-thread-26/ERROR]: Cannot load plugins\UndineMailer\mail\00000366.yml
org.bukkit.configuration.InvalidConfigurationException: could not determine a constructor for the tag tag:yaml.org,2002:org.bukkit.potion.PotionType
 in 'string', line 14, column 18:
        potion_type: !!org.bukkit.potion.PotionType ' ... 
                     ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bitbucket.ucchy.undine.MailData.load(MailData.java:232) [UndineMailer.jar:?]
	at org.bitbucket.ucchy.undine.MailManager$1.run(MailManager.java:89) [UndineMailer.jar:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_05]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: could not determine a constructor for the tag tag:yaml.org,2002:org.bukkit.potion.PotionType
 in 'string', line 14, column 18:
        potion_type: !!org.bukkit.potion.PotionType ' ... 
                     ^

	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:501) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:485) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:485) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:485) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-7297fbd-8047b0a]
	... 10 more

</pre>

**Comment by ucchyocean** [comment]
Fixed
