### ISSUE TITLE
Issue of the co-operation with UltimateCore

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/UndineMailer#46]
At Bukkit starting up, the following error message was written.

<pre>
[02:06:37 ERROR]: Error occurred while enabling UndineMailer v1.4.2 (Is it up to date?)
java.lang.NullPointerException
	at bammerbom.ultimatecore.bukkit.api.UEconomy.isEnabled(UEconomy.java:64) ~[?:?]
	at org.bitbucket.ucchy.undine.bridge.VaultEcoBridge.load(VaultEcoBridge.java:43) ~[?:?]
	at org.bitbucket.ucchy.undine.UndineMailer.onEnable(UndineMailer.java:58) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.3.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.3.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.3.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.3.jar:git-Spigot-529ff99-2acb9e4]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.3.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot-1.8.3.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot-1.8.3.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.8.3.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot-1.8.3.jar:git-Spigot-529ff99-2acb9e4]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.8.3.jar:git-Spigot-529ff99-2acb9e4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
</pre>

**Comment by ucchyocean** [comment]
Fixed
I inserted the workarround for this issue.
