### ISSUE TITLE
Change player listing to light weight.

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/UndineMailer#47]
Changing player listing to light weight.

Now, player list feature of UndineMailer is verrrrry heavy.
So, some users could not listing by ConcurrentModificationException.

<pre>
[17:15:12 INFO]: Androkai issued server command: /uindex /umail to 1
[17:15:12 WARN]: Exception in thread "Craft Scheduler Thread - 54"
[17:15:12 WARN]: org.apache.commons.lang.UnhandledException: Plugin UndineMailer v1.4.3 generated an exception while executing task 29542
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
        at java.util.LinkedList$ListItr.next(LinkedList.java:886)
        at com.google.common.collect.Iterators$9.next(Iterators.java:939)
        at com.google.common.collect.Iterators.addAll(Iterators.java:357)
        at com.google.common.collect.Lists.newArrayList(Lists.java:147)
        at net.minecraft.server.v1_8_R2.UserCache.a(UserCache.java:243)
        at net.minecraft.server.v1_8_R2.UserCache.c(UserCache.java:224)
        at net.minecraft.server.v1_8_R2.UserCache.getProfile(UserCache.java:153)
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.getOfflinePlayer(CraftServer.java:1304)
        at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:741)
        at org.bitbucket.ucchy.undine.command.ListCommand.getAllValidPlayerNames(ListCommand.java:208)
        at org.bitbucket.ucchy.undine.command.ListCommand.access$000(ListCommand.java:30)
        at org.bitbucket.ucchy.undine.command.ListCommand$1.run(ListCommand.java:74)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
</pre>

**Comment by ucchyocean** [comment]
Fixed.
