### ISSUE TITLE
Cannot load on CB172

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/UndineMailer#51]
Cannot load on CB172.

UndineMailer v1.4.5 was OK, but UndineMailer v1.4.6 was NG.
<pre>
[23:50:33] [Server thread/ERROR]: Error occurred while enabling UndineMailer v1.4.6 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/Reader;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at org.bitbucket.ucchy.undine.Messages.<init>(Messages.java:52) ~[?:?]
	at org.bitbucket.ucchy.undine.Messages.reload(Messages.java:184) ~[?:?]
	at org.bitbucket.ucchy.undine.UndineMailer.onEnable(UndineMailer.java:79) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250) ~[spigot-1.7.2-R0.4-SNAPSHOT.jar:git-Spigot-1320]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:350) [spigot-1.7.2-R0.4-SNAPSHOT.jar:git-Spigot-1320]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:390) [spigot-1.7.2-R0.4-SNAPSHOT.jar:git-Spigot-1320]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugin(CraftServer.java:460) [spigot-1.7.2-R0.4-SNAPSHOT.jar:git-Spigot-1320]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:380) [spigot-1.7.2-R0.4-SNAPSHOT.jar:git-Spigot-1320]
	at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:348) [spigot-1.7.2-R0.4-SNAPSHOT.jar:git-Spigot-1320]
	at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:325) [spigot-1.7.2-R0.4-SNAPSHOT.jar:git-Spigot-1320]
	at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:281) [spigot-1.7.2-R0.4-SNAPSHOT.jar:git-Spigot-1320]
	at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:186) [spigot-1.7.2-R0.4-SNAPSHOT.jar:git-Spigot-1320]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:437) [spigot-1.7.2-R0.4-SNAPSHOT.jar:git-Spigot-1320]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot-1.7.2-R0.4-SNAPSHOT.jar:git-Spigot-1320]

</pre>

**Comment by ucchyocean** [comment]
Fixed
