### ISSUE TITLE
コンソールで本文なしのメールを送信しようとするとエラーが起こる

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/UndineMailer#56]
Exception の内容は次の通り

----

<pre>
[22:28:57] [Server thread/WARN]: Unexpected exception while parsing console command "mail send"
org.bukkit.command.CommandException: Unhandled exception executing command 'mail' in plugin UndineMailer v1.4.11
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-d97e08b-5e85956]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-d97e08b-5e85956]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:619) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-d97e08b-5e85956]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:605) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:371) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:336) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-d97e08b-5e85956]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_05]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_05]
	at org.bitbucket.ucchy.undine.MailData.getInboxSummary(MailData.java:849) ~[?:?]
	at org.bitbucket.ucchy.undine.MailManager.sendNewMail(MailManager.java:276) ~[?:?]
	at org.bitbucket.ucchy.undine.command.UndineSendCommand.runCommand(UndineSendCommand.java:279) ~[?:?]
	at org.bitbucket.ucchy.undine.command.UndineCommand.onCommand(UndineCommand.java:89) ~[?:?]
	at org.bitbucket.ucchy.undine.UndineMailer.onCommand(UndineMailer.java:125) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-d97e08b-5e85956]
	... 8 more
</pre>

**Comment by ucchyocean** [comment]
コンソールからの /mail write では、本文が0行のケースがある。
MailManager クラスの sendNewMail で、メッセージ0行の場合にメッセージを強制的に1行追加するように変更すればいいのではないか。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
