### ISSUE TITLE
PaperSpigotでUndineMailerを動作させると、特定の操作をしたときにサーバーコンソールにエラーが記録される。

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/UndineMailer#72]
この障害は、プルリクエスト #71 にて報告された。

特定の操作とは、具体的には次の通り。
- 未読のメールがある状態のプレイヤーがログインしたときに、未読メールの通知が行われた時。
- 新規参加プレイヤーが参加したときに、ウェルカムメールが送信された時。
- プレイヤー名簿が有効な状態で、プレイヤー名簿を表示した時。

これらに共通することは、いずれも非同期処理スレッド内の処理から、tellrawコマンドで画面を表示しているということ。

エラーメッセージは下記のとおり。
<pre>
[19:35:05] [Server thread/INFO]: ucchy[/127.0.0.1:58349] logged in with entity id 283 at ([world]154.5, 80.0, 260.5)
[19:35:28] [Craft Scheduler Thread - 1/ERROR]: Command Dispatched Async: tellraw Player244 {"text":"","extra":[{"text":"§7| "},{"text":"[1]","color":"aqua","clickEvent":{"action":"run_command","value":"/umail read 1"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"このメールを開く"}]}}},{"text":"*"},{"text":"§6CONSOLE (01/13 19:35) ←番号をクリックで開きます。"}]}
[19:35:28] [Craft Scheduler Thread - 1/ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:647) [paperspigot-1.8.8.jar:git-PaperSpigot-56c14f8-07c3001]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:575) [paperspigot-1.8.8.jar:git-PaperSpigot-56c14f8-07c3001]
	at org.bitbucket.ucchy.undine.tellraw.MessageComponent.sendCommand(MessageComponent.java:129) [UndineMailer.jar:?]
	at org.bitbucket.ucchy.undine.tellraw.MessageComponent.send(MessageComponent.java:72) [UndineMailer.jar:?]
	at org.bitbucket.ucchy.undine.MailManager.sendMailLine(MailManager.java:1472) [UndineMailer.jar:?]
	at org.bitbucket.ucchy.undine.MailManager.sendNewMail(MailManager.java:285) [UndineMailer.jar:?]
	at org.bitbucket.ucchy.undine.UndineListener$2.run(UndineListener.java:98) [UndineMailer.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [paperspigot-1.8.8.jar:git-PaperSpigot-56c14f8-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [paperspigot-1.8.8.jar:git-PaperSpigot-56c14f8-07c3001]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_05]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
[19:35:35] [Craft Scheduler Thread - 1/ERROR]: Command Dispatched Async: tellraw ucchy {"text":"","extra":[{"text":"§7| "},{"text":"[2]","color":"aqua","clickEvent":{"action":"run_command","value":"/umail read 2"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"このメールを開く"}]}}},{"text":"*"},{"text":"§6CONSOLE (01/13 19:35) ←番号をクリックで開きます。"}]}
[19:35:35] [Craft Scheduler Thread - 1/ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:647) [paperspigot-1.8.8.jar:git-PaperSpigot-56c14f8-07c3001]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:575) [paperspigot-1.8.8.jar:git-PaperSpigot-56c14f8-07c3001]
	at org.bitbucket.ucchy.undine.tellraw.MessageComponent.sendCommand(MessageComponent.java:129) [UndineMailer.jar:?]
	at org.bitbucket.ucchy.undine.tellraw.MessageComponent.send(MessageComponent.java:72) [UndineMailer.jar:?]
	at org.bitbucket.ucchy.undine.MailManager.sendMailLine(MailManager.java:1472) [UndineMailer.jar:?]
	at org.bitbucket.ucchy.undine.MailManager.sendNewMail(MailManager.java:285) [UndineMailer.jar:?]
	at org.bitbucket.ucchy.undine.UndineListener$2.run(UndineListener.java:98) [UndineMailer.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [paperspigot-1.8.8.jar:git-PaperSpigot-56c14f8-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [paperspigot-1.8.8.jar:git-PaperSpigot-56c14f8-07c3001]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_05]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
</pre>

なお、PaperSpigot以外のサーバー（CraftBukkitやSpigot）では、これらの操作によるコンソールエラー現象は確認できなかった。

**Comment by ucchyocean** [comment]
エラーメッセージにも書かれているとおり、
<pre>
[19:35:35] [Craft Scheduler Thread - 1/ERROR]: Command Dispatched Async: （コマンド略）
[19:35:35] [Craft Scheduler Thread - 1/ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
</pre>
非同期処理の中から Bukkit.dispatchCommand メソッドを呼び出ししたときに、コンソールに警告を吐くような実装を、PaperSpigot内に組み込んでいるようである。
正直なところ、このtellraw処理は非同期で処理することを想定しており、問題が無いことも確認がとれているが、PaperSpigotの警告処理を回避するために対策をせざるを得ない状況である。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK。
確認に使用した PapaerSpigot のバージョンは、`PaperSpigot-56c14f8-07c3001 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`

**Comment by RoboMWM** [comment]
Here's some extra information regarding the effects of this happening in-game **prior** to this fix (meaning the issue is resolved in 1.5.3. I'm just adding this here to show the effects of when it was dispatched async in-game):
Mail edit mode's interface would show up out of order:
http://i.imgur.com/d4aXkk5.png and http://i.imgur.com/RjtBiYA.png

**Comment by ucchyocean** [comment]
RoboMWM,

OK, I will fix your issue in issue #73.

Please do not report the bug in the closed issue...

**Comment by RoboMWM** [comment]
No - I was stating that this was an effect of this issue before it was fixed for documenting purposes

**Comment by ucchyocean** [comment]
Oh, really?

If you can, please try 1.5.4 also. I rollbacked the modification of 1.5.3, and fixed the tread issue by using other method. (And I tested it on PaperSpigot.)

**Comment by RoboMWM** [comment]
Yea, sorry about the confusion. I'll give it a go.

**Comment by RoboMWM** [comment]
1.5.4 Seems to be good to go on my end

**Comment by ucchyocean** [comment]
Nice!
Thank You so much.
