### ISSUE TITLE
Splatoon in Minecraft と一緒に導入すると正しく動作しない

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/UndineMailer#74]
Splatoon in Minecraft と一緒に導入すると、各種コマンドの実行時にエラーが発生して正しく動作しなくなる。

Splatoon in Minecraft と、Undine Mailer を一緒に導入した後、`/mail `コマンドを実行すると、下記のような例外が記録される。
<pre>
[01:26:12] [Server thread/INFO]: ---------- 受信箱 (未読 0通) ----------
[01:26:12] [Server thread/WARN]: Unexpected exception while parsing console command "mail"
org.bukkit.command.CommandException: Unhandled exception executing command 'mail' in plugin UndineMailer v1.5.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NoSuchMethodError: org.bitbucket.ucchy.undine.tellraw.MessageComponent.send(Lorg/bitbucket/ucchy/undine/sender/MailSender;)V
	at org.bitbucket.ucchy.undine.MailManager.sendPager(MailManager.java:1541) ~[?:?]
	at org.bitbucket.ucchy.undine.MailManager.displayInboxList(MailManager.java:576) ~[?:?]
	at org.bitbucket.ucchy.undine.command.UndineInboxCommand.runCommand(UndineInboxCommand.java:76) ~[?:?]
	at org.bitbucket.ucchy.undine.command.UndineCommand.onCommand(UndineCommand.java:74) ~[?:?]
	at org.bitbucket.ucchy.undine.UndineMailer.onCommand(UndineMailer.java:125) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	... 8 more

</pre>

**Comment by ucchyocean** [comment]
どうやら、Splatoon in Minecraft の中に `org.bitbucket.ucchy.undine.tellraw.MessageComponent` のコピーが入っているらしく、そのコピーでは、UndineMailer に依存しているメソッド `send(Lorg/bitbucket/ucchy/undine/sender/MailSender;)V` が削除されてしまっているようだ。
そのため、Splatoon in Minecraft の中にある MessageComponent が、UndineMailerから実行されてしまうと、該当のメソッドが見つからずに例外終了してしまう。

そもそも、MessageComponent の中に1つだけ UndineMailer に依存したメソッドが居ると、再利用性が損なわれて設計上よくない。なので、この機会に、UndineMailer 側のMessageComponent も、該当メソッドを削除する。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
