### ISSUE TITLE
UndineMailer の後に起動した経済プラグインと連携することができない

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/UndineMailer#79]
フォーラムにて報告された不具合。

------

EssentialsからEssentialsXに乗り換えたのですが、プレイヤーから着払い設定がアイテムしかできなくなった(お金で設定できない)と報告を受けました。
乗り換え前は問題なく設定できたようなので修正、確認をお願いいたします。

CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version1.8.8-R0.1-SNAPSHOT)

Plugins (53): NekoEvent, KeepItems, ScheduledAnnouncer2, DKLib, SuperTrails, BossBarAPI, NoteBlockAPI, Simple-AutoSave, TSP_A_StealPlayerHead, dynmap, WorldEdit, OpenInv, ClearLag, TheEndAgain, Chairs, NoteBlockPlayer, SetSpawn, Modifyworld, WorldBorder, BuycraftX, Votifier, IronElevators, Multiverse-Core, ProtocolLib, NCore, PermissionsEx, Multiverse-Portals, NekoCore, Vault, BottledExp, GakubuchiLockReloaded, BarAPI, LogBlock, HolographicDisplays, LWC, WorldGuard, SignColors,MythicMobs, LunaChat, RemoteController, CookieMonster, SimpleVoteListener, UndineMailer, MyPet, Essentials, MCBans, BlockHat, Jobs, TNTRun, VanishNoPacket, HeavySpleef, ChestShop, BlockParty

EssentialsX: https://www.spigotmc.org/resources/essentialsx.9089/

追記：
[着払い料金を設定する]は表示されないが/umail costmoney を実行することは可能。
実行した場合、受け取り時に下記の例外が発生。

<pre>
>2016-04-05 18:46:16,580 ERROR An exception occurred processing Appender RemoteController java.lang.NullPointerException

[18:46:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'umail' in plugin UndineMailer v1.5.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
at org.bitbucket.ucchy.undine.command.UndineAttachCommand.checkForCostMoney(UndineAttachCommand.java:380) ~[?:?]
at org.bitbucket.ucchy.undine.command.UndineAttachCommand.runCommandForSentMail(UndineAttachCommand.java:352) ~[?:?]
at org.bitbucket.ucchy.undine.command.UndineAttachCommand.runCommand(UndineAttachCommand.java:199) ~[?:?]
at org.bitbucket.ucchy.undine.command.UndineCommand.onCommand(UndineCommand.java:90) ~[?:?]
at org.bitbucket.ucchy.undine.UndineMailer.onCommand(UndineMailer.java:126) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
... 15 more
</pre>

**Comment by ucchyocean** [comment]
どうやら、EssentialsX の起動を待つことなく UndineMailer が動作してしまっているため、経済プラグイン連携時に相手がEnabledになっているかチェックするところでfalseが帰ってきており、連携が行われない模様。
Vaultの仕様が変更になったのかな・・・？
とはいえ、UndineMailerで、連携先経済プラグインが有効かどうかチェックする箇所をなくしてしまえば、問題は解決しそう。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
